name: gbintk
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.9,<3.13
  - flit
  - click
  - biopython
  - python-igraph
  - cairo
  - pkg-config
  - fraggenescan
  - hmmer
  - networkx
  - scipy
  - numpy
  - pandas
  - tqdm
  - pip
  - pip:
    - .
